### ISSUE TITLE
upload and import question

### ISSUE THREAD

**Issue by Log-of-e** [tefkah/pubpub-client#4]
Hi
 Thank you for taking the time to make this client SDK.
I am having trouble with upload and import. Maybe you have some tips on what I am missing or where I could look?

I use the uploadFile method and the file appears as an asset but is not linked to my pubpub homepage, and only has a key not a pubpu id, so I would like to figure out how to link it to my page as a pubpub not just a raw asset:

```ts
 const uploadedFile = await pubpub.uploadFile({
      file: fileOrPath,
      fileName,
      mimeType,
    })

result:
uploadedFile :: {
  url: 'https://assets.pubpub.org/tXXXXXXv/50000000000001.pdf',
  size: 28000,
  key: 'tXXXXXXv/50000000000001.pdf',
  data: ''
}
```

As an alternative tried to use the import example from test.test.ts, maybe I made the testurl in a bad way? Or I skipped a preparation step?:

```ts
   const testUrl = 'pub/33g2dary/draft'

  const imported = await pubpub.pub.hacks.import(
      testUrl,
      [
        {
          file: fileURLToPath(new URL('./basic.docx', import.meta.url)),
          fileName: 'basic.docx',
          mimeType:
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        },
      ],
      (doc, schema) => {
        console.dir(doc, { depth: 5 })
        const newDoc = doc.addToEnd(
          schema.nodes.paragraph.create(
            { id: 'test-id' },
            schema.text('manually insterted text')
          )
        )
        console.dir(newDoc, { depth: 5 })
        return newDoc
      }
    )
```

I end up with an error. First few lines of error log:

```log
AxiosError: Request failed with status code 404
    at settle (file:///Users/nesim/projects/proto02/pubpubtest01/node_modules/pubpub-client/node_modules/axios/lib/core/settle.js:19:12)
    at BrotliDecompress.handleStreamEnd (file:///Users/nesim/projects/proto02/pubpubtest01/node_modules/pubpub-client/node_modules/axios/lib/adapters/http.js:570:11)
    at BrotliDecompress.emit (node:events:523:35)
    at endReadableNT (node:internal/streams/readable:1367:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      Cookie: 'pp-cache=pp-no-cache; Max-Age=2592000; Domain=.pubpub.org; Path=/; Expires=Fri, 30 Jun 2023 20:07:00 GMT; connect.sid=s%3As88U6QJ-edYuB9z7p3yjYaXnKxGF0IXA.ZufgTZ9Y9YFfOGuIJxqcs%2BRFYqb%2BcVvNIJxEt9Tus1U; Domain=.pubpub.org; Path=/; Expires=Fri, 30 Jun 2023 20:07:00 GMT',
      'User-Agent': 'axios/1.4.0',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'https://testabcd123456789.pubpub.org/pub/33g2dary/draft',
    data: undefined
  },

```

**Comment by Log-of-e** [comment]
I found the workaround for using import is to first get a valid slug for the url to import. The first step is to POST to "https://testabcd123456789.pubpub.org/api/pubs" using the arguments I found in the browser network tab, which returns a slug as well as other metadata. 
Then I can use the slug to import data to the url/testUrl field for the hacks.import method: `pub/<SLUG>/drafts`

I did see what look like create methods in this SDK, so hopefully the initial POST is already baked in somewhere.

 @daaronr

**Comment by tefkah** [comment]
Hey, thanks for the report!
You should not use the `upload` method directly, are you using an old version of the SDK? I thought I privated that.
If you want to import a pub you indeed first have to create it, then import data. This is also how it is done on the pubpub frontend (you first click "Create Pub" and then you import stuff).

I agree that this is not the most ergonomic, and in the future this client will feature more ergonomic methods to do things with the API.

I have recently been hired to work on this client by PubPub, so I'll have a lot of time to iron out unergonomic points like these, so feel free to continue to post these questions!
