### ISSUE TITLE
login broken by possible HTTP header changes

### ISSUE THREAD

**Issue by Log-of-e** [tefkah/pubpub-client#5]
The login method looks to be broken by possible HTTP header changes

I ll gather details and send here.

**Comment by tefkah** [comment]
Are you using the latest version? There was a change recently but it should be fixed

**Comment by Log-of-e** [comment]
Yes on  version 0.7.0 from npm. The only change since then was to the Readme.
I also checked the version I am using from npm has the typeguards from May 3 commit  83d2f8d

Using fetch with the following headers (and cookie) seems to work:

```
   "headers": {
    "accept": "application/json",
    "cache-control": "no-cache",
    "content-type": "application/json",
    "pragma": "no-cache"
    }
```

  There are axios common default headers being set somewhere, which get added to the ones set by the client code, but I cannot find where they are being set.
  
  AxiosError: Request failed with status code 403
    code: 'ERR_BAD_REQUEST',

    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/1.4.0',
      'Content-Length': '178',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'post',

**Comment by tefkah** [comment]
Also btw for what request does it fail? I do intend to add better error messages in the future, but given that its a post request I'm guessing you are trying to create a pub?

**Comment by Log-of-e** [comment]
Thanks so much I ll give it a test run.

I could not get either login or logout to work with the library using Axios, so I did the above successful test with Nodejs fetch.

This API client library will be used for a command line utility and server side.
Some of the command functional requirements might fit into this API SDK.
You can read some of the code and requirements: https://github.com/Log-of-e/pubpubutil/wiki

This software  is to support the https://unjournal.pubpub.org/, https://effective-giving-marketing.gitbook.io/unjournal-x-ea-and-global-priorities-research/readme-1. The aims are to reduce publishing delays, reduce costs to academics, increase quality of reviews, and thereby increase awareness and distribution for quality academic scholarship. 

@daaronr

**Comment by Log-of-e** [comment]
testing in progress
