### ISSUE TITLE
Question: Preserve or edit media types and iframes

### ISSUE THREAD

**Issue by Log-of-e** [tefkah/pubpub-client#6]
Hi,
  I have a question, when I export and import documents, iframe elements are removed.

Do you have any examples using postprocessing? I would like to import a .docx (or another supported format), search for certain elements such as tables and update attributes such as width, or search for certain text containing urls that I want to put into a media element such as iframe or gist or video element. 
 I am currently trying to figure out search and replace, is it as simple as going through nodes in JSON and just modifying JSON?

 For export, followed by import, I would like to do similar. Or I might want to do programmatic formatting edits to a pub via API to the JSON directly rather than going through import and export.

 Thanks for your help  
 
 CC: @gabestein @daaronr

**Comment by tefkah** [comment]
Hi! You can have a look here for the one I use to sync data from OJS to PubPub.
https://github.com/TrialAndErrorOrg/sync-ojs-pubpub

I import a TeX document through PubPub, which then gets processed using `src/postProcess.ts`

You won't be able to run it, but you can have a look at the different APIs used to transform the content.

I would recommend looking through prosemirrors docs here: https://prosemirror.net/docs/ref/#model.DOM_Representation

At the moment there isn't a method to directly edit the contents of a document through the API client, although this is something I would like to support in the future.

**Comment by Log-of-e** [comment]
Thank you for the links!
